// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_layout.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/account/_middleware.ts";
import * as $5 from "./routes/account/myshorts.tsx";
import * as $6 from "./routes/callback.ts";
import * as $7 from "./routes/index.tsx";
import * as $8 from "./routes/s/[id].tsx";
import * as $9 from "./routes/signin.ts";
import * as $10 from "./routes/signout.ts";
import * as $$0 from "./islands/Short.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_layout.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/account/_middleware.ts": $4,
    "./routes/account/myshorts.tsx": $5,
    "./routes/callback.ts": $6,
    "./routes/index.tsx": $7,
    "./routes/s/[id].tsx": $8,
    "./routes/signin.ts": $9,
    "./routes/signout.ts": $10,
  },
  islands: {
    "./islands/Short.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
